# Generated by Django 5.0.7 on 2024-09-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
