# Generated by Django 5.1.1 on 2024-10-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='line',
            field=models.CharField(max_length=100),
        ),
    ]
