# Generated by Django 5.1.1 on 2024-10-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_station_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='sort_order',
        ),
    ]
