# Generated by Django 5.1.1 on 2024-10-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0007_remove_station_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
