# Generated by Django 5.1.1 on 2024-10-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0008_station_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='sort_order',
            field=models.IntegerField(),
        ),
    ]
